### ISSUE TITLE
cant install package

### ISSUE THREAD

**Issue by fasaya** [yaza-putu/laravel-repository-with-service#1]
Problem 1
    - Root composer.json requires yaza/laravel-repository-service ^1.5 -> satisfiable by yaza/laravel-repository-service[V1.5.15].
    - yaza/laravel-repository-service V1.5.15 requires illuminate/contracts ^8.37 -> found illuminate/contracts[v8.37.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

i’m using laravel 9, and cannot install illuminate/contracts at the same time
Only one of these can be installed: laravel/framework[v8.0.0, ..., 8.x-dev], illuminate/contracts[v9.0.0]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.

**Comment by theeldarka** [comment]
@yaza-putu Add Laravel 9 support, please

**Comment by yaza-putu** [comment]
Thanks for your report, i'll try to fix this problem to support laravel 9.

Pada tanggal Sel, 22 Mar 2022 22.35, theeldarka ***@***.***>
menulis:

**Comment by yaza-putu** [comment]
update to support laravel 9 finish
