### ISSUE TITLE
untuk create dan update pada service kenapa tidak di return ya?

### ISSUE THREAD

**Issue by manusiakemos** [yaza-putu/laravel-repository-with-service#11]
<img width="496" alt="image" src="https://github.com/yaza-putu/laravel-repository-with-service/assets/31971611/06303b17-356d-4a6b-9cf3-1e2c3870ed31">

**Comment by yaza-putu** [comment]
untuk sekarang belum bisa service return data tapi bisa pakai setter getter service ya ada di dokumentasi https://yaza-putu.github.io/guide/Service.html#example-code-rest-api-service nanti tinggal panggil $namaService->getResult();
