### ISSUE TITLE
Documentation Link Invalid

### ISSUE THREAD

**Issue by MdAnowarHosen** [yaza-putu/laravel-repository-with-service#13]
When I open the documentation link it shows: "Warning: This URL has been blocked by Bitly's systems as potentially harmful".

**Comment by yaza-putu** [comment]
Sorry link expired, yoh can visit https://yaza-putu.github.io/
For the documentation

Pada tanggal Sab, 2 Mar 2024 14.01, Anowar Hosen ***@***.***>
menulis:
