### ISSUE TITLE
Generate service Api

### ISSUE THREAD

**Issue by damaskus92** [yaza-putu/laravel-repository-with-service#16]
Untuk generate service  dengan command **--api** tidak bisa mas

![Screenshot from 2024-04-22 21-40-22](https://github.com/yaza-putu/laravel-repository-with-service/assets/53900364/f5a2af14-6ff8-45cc-bb96-f38e5b3146b2)

**Comment by yaza-putu** [comment]
Untuk versi yang terbaru sekarang secara default ketika membuat service
menggunakan template --api

Jadi sudah tidak perlu lagi memanggil --api. Tapi jika ingin menggunakan
template kosong cukup isikan --blank. Pada readme.md sudah saya isikan ya
mas. Semoga membantu

Pada tanggal Sen, 22 Apr 2024 22.44, Damas Eka K ***@***.***>
menulis:

**Comment by damaskus92** [comment]
Baik mas terimakasih
