### ISSUE TITLE
Argument --service error on linux

### ISSUE THREAD

**Issue by ariexx** [yaza-putu/laravel-repository-with-service#5]
Halo mas, ini saya dulu pake windows tapi udh migrasi ke linux, ketika make command --service saya menemukan package ini membuat folder App baru didalam directory laravel.

Untuk di linux saya harus membuat folder berdasarkan nama model agar bisa menggunakan argument --service.

**Comment by yaza-putu** [comment]
kalau membuat argument service itu harus dibarengi dengan pembuatan repository bang..
ex: php artisan make:repository NamaRepository --service, kalau nama service berbeda dengan nama model / repository abang cukup rubah di constructor service dan repository.. 

kalau nama model dengan nama repository sama tidak perlu seting path model di repository jika beda perlu di definisikan bang modelnya di repository

kalau nama service dengan repository berbeda abang perlu seting repositorynya di constructor  service bang..


masalahnya error pas buat atau apa bang..?


kalau case seperti yg saya katakan diatas cukup perbaiki pendefinisian yg diperlukan

**Comment by yaza-putu** [comment]
sudah saya solve di versi 5 ya
