### ISSUE TITLE
Error create service

### ISSUE THREAD

**Issue by jrpikong** [yaza-putu/laravel-repository-with-service#6]
error if run : ``sail artisan make:repository UserRepository --service`` or want to generate service
  file_put_contents(/var/www/html/app/Services/User/UserService.php): Failed to open stream: No such file or directory
@yaza-putu

**Comment by yaza-putu** [comment]
ok siap bang thanks reportnya, nanti saya cek.. ini tidak jalan di linux bang?
kalau boleh tahu linux apa?

**Comment by nashrullohmukti1** [comment]
linux 20.04 seperti ini

**Comment by jrpikong** [comment]
Linux 22.04 sama aja, selain itu membuat folder App .
Bisa dicoba jalanin laravel pakai laravel sail biar dapat ubuntu

**Comment by izzelislam** [comment]
![Screenshot from 2023-01-28 18-04-41](https://user-images.githubusercontent.com/45987491/215263194-d2169f61-151c-4747-9568-d58bb2ceaafb.png)


permisi mohon bantuannya bang saya mengalami error seperti ini saat mau generate service , laravel v 9, php v 8.1 dan os linux ubuntu 22.10. @yaza-putu .

**Comment by zikrisuanda11** [comment]
sama bang saya juga ngalamin os Ubuntu 22.04.2 LTS jadi setiap kelar eksekusi artisan hapus folder App sama sebelum eksekusi buat folder Servicenya dulu biar gk error

**Comment by izzelislam** [comment]
> 

Oo berarti Didalam App bikin direktoro service dulu ya bang?

**Comment by zikrisuanda11** [comment]
yoi bang

**Comment by cakmalik** [comment]
Linux mint gitu juga bang. thanks

**Comment by yaza-putu** [comment]
sudah saya solve di versi 5 ya
