### ISSUE TITLE
Bagaimana cara mengakses repository di seeder?

### ISSUE THREAD

**Issue by fdjrr** [yaza-putu/laravel-repository-with-service#9]
Saat mengakses repository di file seeder muncul error, solusinya gimana ya mas?

**Comment by yaza-putu** [comment]
Kalau saya di seeder tidak manggil repository tapi langsung modelnya...

Karena dalam seeder cuma manggil insert atai find aja

Pada tanggal Sen, 16 Okt 2023 11.49, Fadjrir Herlambang <
***@***.***> menulis:

**Comment by fdjrr** [comment]
kalo di view bladenya gimana mas? bisa ngga? atau pake model?

**Comment by yaza-putu** [comment]
Ini sudah melenceng dari konsep repository dan service pattern mas

View hanya nerima data dari controller

Service di panggil dari controller
Dan repository di panggil dari service

Pada tanggal Sel, 17 Okt 2023 11.49, Fadjrir Herlambang <
***@***.***> menulis:
